version: 0.0.{build}

branches:
  only:
    - master
    - develop
    - ci-test

skip_commits:
  files:
    - docs/**/*
    - .editorconfig
    - .gitattributes
    - .gitignore
    - .travis.yml
    - LICENSE
    - README.md
    - rocro.yml

image:
  - Visual Studio 2019
  - Visual Studio 2017

environment:
  global:
    PYTHON: "C:\\Python35"

  matrix:
    - CXX_STANDARD: 14
    - CXX_STANDARD: 17
    - CXX_STANDARD: 20

platform:
  - x64
  - Win32

configuration:
  - Debug
  - Release

build:
  parallel: true
  verbosity: minimal
  project: build/bksge.sln

install:
- ps: |
    Write-Output "Generator: $env:CMAKE_GENERATOR"
    Write-Output "CXX_STANDARD: $env:CXX_STANDARD"
    Write-Output "Platform: $env:platform"
    Write-Output "Configuation: $env:configuration"
    Write-Output "Env: $env"

before_build:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" (set CMAKE_GENERATOR="Visual Studio 16 2019")
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (set CMAKE_GENERATOR="Visual Studio 15 2017")
  - echo CMAKE_GENERATOR=%CMAKE_GENERATOR%
  - mkdir build
  - cd build
  - cmake .. -G %CMAKE_GENERATOR% -A "%PLATFORM%" -DBKSGE_UNITY_BUILD=ON -DCMAKE_CXX_STANDARD="%CXX_STANDARD%" -DCMAKE_BUILD_TYPE="%CONFIGURATION%" -DCMAKE_CONFIGURATION_TYPES=Debug;Release -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"
  - echo Building platform=%PLATFORM% configuration=%CONFIGURATION%

test_script:
- ps: |
    & ctest -C $env:configuration -j $env:NUMBER_OF_PROCESSORS --timeout 6000 --output-on-failure -T Test
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }

    $XSLInputElement = New-Object System.Xml.Xsl.XslCompiledTransform
    $XSLInputElement.Load("https://raw.githubusercontent.com/rpavlik/jenkins-ctest-plugin/master/ctest-to-junit.xsl")
    $XSLInputElement.Transform((Resolve-Path .\Testing\**\*.xml), (Join-Path (Resolve-Path .) "ctest-to-junit-results.xml"))
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\ctest-to-junit-results.xml))

artifacts:
  - path: 'build/CMakeFiles/*.log'
    name: logs
  - path: 'build/Testing/**/*.xml'
    name: test_results
