/**
 *	@file	for_each_product.hpp
 *
 *	@brief
 *
 *	@author	myoukaku
 */

#ifndef BKSGE_FND_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
#define BKSGE_FND_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
#
# include <bksge/fnd/preprocessor/arithmetic/dec.hpp>
# include <bksge/fnd/preprocessor/config/config.hpp>
# include <bksge/fnd/preprocessor/control/if.hpp>
# include <bksge/fnd/preprocessor/repetition/for.hpp>
# include <bksge/fnd/preprocessor/seq/seq.hpp>
# include <bksge/fnd/preprocessor/seq/size.hpp>
# include <bksge/fnd/preprocessor/tuple/elem.hpp>
# include <bksge/fnd/preprocessor/tuple/rem.hpp>
#
# /* BKSGE_PP_SEQ_FOR_EACH_PRODUCT */
#
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT(macro, sets) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_E(BKSGE_PP_FOR, macro, sets)
#
# /* BKSGE_PP_SEQ_FOR_EACH_PRODUCT_R */
#
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_R(r, macro, sets) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_E(BKSGE_PP_FOR_ ## r, macro, sets)
#
# if ~BKSGE_PP_CONFIG_FLAGS() & BKSGE_PP_CONFIG_EDG()
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) impl((BKSGE_PP_SEQ_HEAD(sets)(nil), BKSGE_PP_SEQ_TAIL(sets)(nil), (nil), macro), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# else
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets)
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets) impl((BKSGE_PP_SEQ_HEAD(sets)(nil), BKSGE_PP_SEQ_TAIL(sets)(nil), (nil), macro), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# endif
#
# if BKSGE_PP_CONFIG_FLAGS() & BKSGE_PP_CONFIG_STRICT()
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P_I data
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P_I(cset, rset, res, macro) BKSGE_PP_DEC(BKSGE_PP_SEQ_SIZE(cset))
# else
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) BKSGE_PP_DEC(BKSGE_PP_SEQ_SIZE(BKSGE_PP_TUPLE_ELEM(4, 0, data)))
# endif
#
# if ~BKSGE_PP_CONFIG_FLAGS() & BKSGE_PP_CONFIG_MWCC()
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O_I data
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O_I(cset, rset, res, macro) (BKSGE_PP_SEQ_TAIL(cset), rset, res, macro)
# else
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) (BKSGE_PP_SEQ_TAIL(BKSGE_PP_TUPLE_ELEM(4, 0, data)), BKSGE_PP_TUPLE_ELEM(4, 1, data), BKSGE_PP_TUPLE_ELEM(4, 2, data), BKSGE_PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, i) BKSGE_PP_IF(BKSGE_PP_DEC(BKSGE_PP_SEQ_SIZE(BKSGE_PP_TUPLE_ELEM(4, 1, data))), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_ ## i, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I)
#
# if ~BKSGE_PP_CONFIG_FLAGS() & BKSGE_PP_CONFIG_EDG()
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, BKSGE_PP_TUPLE_ELEM(4, 0, data), BKSGE_PP_TUPLE_ELEM(4, 1, data), BKSGE_PP_TUPLE_ELEM(4, 2, data), BKSGE_PP_TUPLE_ELEM(4, 3, data))
# else
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, BKSGE_PP_TUPLE_REM_4 data)
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, im) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, im)
# endif
#
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, cset, rset, res, macro) macro(r, BKSGE_PP_SEQ_TAIL(res (BKSGE_PP_SEQ_HEAD(cset))))
#
# if ~BKSGE_PP_CONFIG_FLAGS() & BKSGE_PP_CONFIG_MWCC()
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H_I data
# else
#    define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H_I(BKSGE_PP_TUPLE_ELEM(4, 0, data), BKSGE_PP_TUPLE_ELEM(4, 1, data), BKSGE_PP_TUPLE_ELEM(4, 2, data), BKSGE_PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H_I(cset, rset, res, macro) (BKSGE_PP_SEQ_HEAD(rset)(nil), BKSGE_PP_SEQ_TAIL(rset), res (BKSGE_PP_SEQ_HEAD(cset)), macro)
#
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_0(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 0)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_1(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 1)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_2(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 2)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_3(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 3)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_4(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 4)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_5(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 5)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_6(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 6)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_7(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 7)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_8(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 8)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_9(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 9)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_10(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 10)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_11(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 11)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_12(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 12)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_13(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 13)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_14(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 14)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_15(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 15)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_16(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 16)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_17(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 17)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_18(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 18)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_19(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 19)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_20(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 20)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_21(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 21)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_22(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 22)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_23(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 23)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_24(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 24)(r, data)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_25(r, data) BKSGE_PP_SEQ_FOR_EACH_PRODUCT_C(data, 25)(r, data)
#
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_0(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_1)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_1(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_2)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_2(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_3)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_3(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_4)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_4(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_5)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_5(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_6)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_6(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_7)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_7(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_8)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_8(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_9)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_9(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_10)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_10(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_11)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_11(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_12)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_12(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_13)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_13(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_14)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_14(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_15)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_15(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_16)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_16(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_17)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_17(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_18)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_18(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_19)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_19(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_20)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_20(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_21)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_21(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_22)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_22(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_23)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_23(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_24)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_24(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_25)
# define BKSGE_PP_SEQ_FOR_EACH_PRODUCT_N_25(r, data) BKSGE_PP_FOR_ ## r(BKSGE_PP_SEQ_FOR_EACH_PRODUCT_H(data), BKSGE_PP_SEQ_FOR_EACH_PRODUCT_P, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_O, BKSGE_PP_SEQ_FOR_EACH_PRODUCT_M_26)
#
#endif // BKSGE_FND_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
