/**
 *	@file	is_begin_parens.hpp
 *
 *	@brief
 *
 *	@author	myoukaku
 */

#ifndef BKSGE_FND_PREPROCESSOR_PUNCTUATION_DETAIL_IS_BEGIN_PARENS_HPP
#define BKSGE_FND_PREPROCESSOR_PUNCTUATION_DETAIL_IS_BEGIN_PARENS_HPP

#if BKSGE_PP_VARIADICS_MSVC

#include <bksge/fnd/preprocessor/facilities/empty.hpp>

#define BKSGE_PP_DETAIL_VD_IBP_CAT(a, b) BKSGE_PP_DETAIL_VD_IBP_CAT_I(a, b)
#define BKSGE_PP_DETAIL_VD_IBP_CAT_I(a, b) BKSGE_PP_DETAIL_VD_IBP_CAT_II(a ## b)
#define BKSGE_PP_DETAIL_VD_IBP_CAT_II(res) res

#define BKSGE_PP_DETAIL_IBP_SPLIT(i, ...) \
    BKSGE_PP_DETAIL_VD_IBP_CAT(BKSGE_PP_DETAIL_IBP_PRIMITIVE_CAT(BKSGE_PP_DETAIL_IBP_SPLIT_,i)(__VA_ARGS__),BKSGE_PP_EMPTY()) \
/**/

#define BKSGE_PP_DETAIL_IBP_IS_VARIADIC_C(...) 1 1

#else

#define BKSGE_PP_DETAIL_IBP_SPLIT(i, ...) \
    BKSGE_PP_DETAIL_IBP_PRIMITIVE_CAT(BKSGE_PP_DETAIL_IBP_SPLIT_,i)(__VA_ARGS__) \
/**/

#define BKSGE_PP_DETAIL_IBP_IS_VARIADIC_C(...) 1

#endif /* BKSGE_PP_VARIADICS_MSVC */

#define BKSGE_PP_DETAIL_IBP_SPLIT_0(a, ...) a
#define BKSGE_PP_DETAIL_IBP_SPLIT_1(a, ...) __VA_ARGS__

#define BKSGE_PP_DETAIL_IBP_CAT(a, ...) BKSGE_PP_DETAIL_IBP_PRIMITIVE_CAT(a,__VA_ARGS__)
#define BKSGE_PP_DETAIL_IBP_PRIMITIVE_CAT(a, ...) a ## __VA_ARGS__

#define BKSGE_PP_DETAIL_IBP_IS_VARIADIC_R_1 1,
#define BKSGE_PP_DETAIL_IBP_IS_VARIADIC_R_BKSGE_PP_DETAIL_IBP_IS_VARIADIC_C 0,

#endif // BKSGE_FND_PREPROCESSOR_PUNCTUATION_DETAIL_IS_BEGIN_PARENS_HPP
