/**
 *	@file	error.hpp
 *
 *	@brief
 *
 *	@author	myoukaku
 */

#ifndef BKSGE_PREPROCESSOR_DEBUG_ERROR_HPP
#define BKSGE_PREPROCESSOR_DEBUG_ERROR_HPP
#
# include <bksge/preprocessor/cat.hpp>
# include <bksge/preprocessor/config/config.hpp>
#
# /* BKSGE_PP_ERROR */
#
# if BKSGE_PP_CONFIG_ERRORS
#    define BKSGE_PP_ERROR(code) BKSGE_PP_CAT(BKSGE_PP_ERROR_, code)
# endif
#
# define BKSGE_PP_ERROR_0x0000 BKSGE_PP_ERROR(0x0000, BKSGE_PP_INDEX_OUT_OF_BOUNDS)
# define BKSGE_PP_ERROR_0x0001 BKSGE_PP_ERROR(0x0001, BKSGE_PP_WHILE_OVERFLOW)
# define BKSGE_PP_ERROR_0x0002 BKSGE_PP_ERROR(0x0002, BKSGE_PP_FOR_OVERFLOW)
# define BKSGE_PP_ERROR_0x0003 BKSGE_PP_ERROR(0x0003, BKSGE_PP_REPEAT_OVERFLOW)
# define BKSGE_PP_ERROR_0x0004 BKSGE_PP_ERROR(0x0004, BKSGE_PP_LIST_FOLD_OVERFLOW)
# define BKSGE_PP_ERROR_0x0005 BKSGE_PP_ERROR(0x0005, BKSGE_PP_SEQ_FOLD_OVERFLOW)
# define BKSGE_PP_ERROR_0x0006 BKSGE_PP_ERROR(0x0006, BKSGE_PP_ARITHMETIC_OVERFLOW)
# define BKSGE_PP_ERROR_0x0007 BKSGE_PP_ERROR(0x0007, BKSGE_PP_DIVISION_BY_ZERO)
#
#endif // BKSGE_PREPROCESSOR_DEBUG_ERROR_HPP
