name: set

on:
  push:

  workflow_dispatch:

jobs:
  windows-test:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x64, Win32]
        cxx_standard: [14, 17, 20]
        build_type: [Debug, Release]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure CMake
        run: cmake ${{github.workspace}}/libs/fnd/set -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -A "${{matrix.architecture}}" -DCMAKE_CXX_STANDARD="${{matrix.cxx_standard}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -j 4 -C ${{matrix.build_type}}

